import {
  FormTemplate,
  ACTION_FORM,
} from 'src/app/modules/group_beta/shared/dynamic/dynamic-form/model/form-template';
import { FieldBase } from 'src/app/modules/group_beta/shared/dynamic/dynamic-form/model/field-base';

// URLs
let urls = {
  search: 'users',
  get: 'users/',
  post: 'users/',
  put: 'users/',
};

// fieldsEdit
let fieldsEdit = [
  new FieldBase<any>({
    required: true,
    url: '',
    text: '',
    controlType: 'textbox',
    key: 'id',
    label: '',
    type: 'hidden',
    value: '',
    order: 101,
    showLabel: false,
    readonly: true,
  }),

  new FieldBase<any>({
    required: true,
    url: '',
    text: '',
    controlType: 'textbox',
    key: 'name',
    label: '',
    type: 'text',
    value: '',
    order: 1,
    showLabel: true,
    readonly: false,
  }),
  new FieldBase<any>({
    required: true,
    url: '',
    text: '',
    controlType: 'select',
    key: 'status',
    label: '',
    type: 'select',
    options: [
      { key: 'pending', value: 'pending' },
      { key: 'enable', value: 'enable' },
      { key: 'disable', value: 'disable' },
    ],
    value: 'enable',
    order: 2,
    showLabel: true,
    readonly: false,
  }),
  new FieldBase<any>({
    required: true,
    url: '',
    text: '',
    controlType: 'select',
    key: 'access',
    label: '',
    type: 'select',
    options: [
      { key: 'administrator', value: 'administrator' },
      { key: 'supervisor', value: 'supervisor' },
      { key: 'operator', value: 'operator' },
      { key: 'customer', value: 'customer' },
      { key: 'user', value: 'user' },
    ],
    value: 'customer',
    order: 3,
    showLabel: true,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: true,
    url: '',
    text: '',
    controlType: 'number',
    key: 'number',
    label: '',
    type: 'text',
    value: '',
    order: 4,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'textbox',
    key: 'sourceName',
    label: '',
    type: '',
    value: '',
    order: 5,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'text',
    key: 'phone',
    label: '',
    type: 'text',
    value: '',
    order: 6,
    readonly: false,
    pattern: '^[+]*[(]{0,1}[0-9]{1,4}[)]{0,1}[-s./0-9]*$',
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'text',
    key: 'email',
    label: '',
    type: 'text',
    value: '',
    order: 7,
    readonly: false,
    pattern:
      "^(?=.{1,254}$)(?=.{1,64}@)[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+(?:.[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+)*@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$",
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'text',
    key: 'username',
    label: '',
    type: 'text',
    value: '',
    order: 8,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: true,
    url: '',
    text: '',
    controlType: 'text',
    key: 'password',
    label: '',
    type: 'password',
    value: '',
    order: 9,
    readonly: false,
    pattern: '^(?=.*[a-zA-Z])(?=.*[0-9]).{6,}$',
    msj: 'La clave debe tener al menos 6 caracteres, contener letras y números'
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'text',
    key: 'notes',
    label: 'Notas',
    type: 'text',
    value: '',
    order: 10,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'link1',
    key: 'link1',
    label: '',
    type: 'text',
    value: '',
    order: 11,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'link2',
    key: 'link2',
    label: '',
    type: 'text',
    value: '',
    order: 12,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'link3',
    key: 'link3',
    label: '',
    type: 'text',
    value: '',
    order: 13,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'link4',
    key: 'link4',
    label: '',
    type: 'text',
    value: '',
    order: 14,
    readonly: false,
  }),
];

// fieldsShow
let fieldsShow = [

  new FieldBase<any>({
    required: true,
    url: '',
    text: '',
    controlType: 'textbox',
    key: 'id',
    label: '',
    type: 'hidden',
    value: '',
    order: 101,
    showLabel: false,
    readonly: true,
  }),
  new FieldBase<any>({
    required: true,
    url: '',
    text: '',
    controlType: 'textbox',
    key: 'status',
    label: 'Estado',
    type: '',
    value: 'title',
    order: 2,
    showLabel: true,
    readonly: true,
  }),
  new FieldBase<any>({
    required: true,
    url: '',
    text: '',
    controlType: 'text',
    key: 'access',
    label: 'Acceso',
    type: 'text',
    value: '',
    order: 3,
    showLabel: true,
    readonly: true,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: true,
    url: '',
    text: '',
    controlType: 'text',
    key: 'username',
    label: 'Usuario',
    type: 'text',
    // options: [{key:'uno', value:'uno'}],
    value: '',
    order: 4,
    readonly: true,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: true,
    url: '',
    text: '',
    controlType: 'number',
    key: 'number',
    label: 'Número',
    type: 'text',
    value: '',
    order: 5,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: true,
    url: '',
    text: '',
    controlType: 'textbox',
    key: 'sourceName',
    label: '',
    type: '',
    value: '',
    order: 6,
    readonly: false,
  }),

  new FieldBase<any>({
    showLabel: true,
    required: true,
    url: '',
    text: '',
    controlType: 'text',
    key: 'phone',
    label: 'Teléfono',
    type: 'text',
    // options: [],
    value: '',
    order: 7,
    readonly: false,
    pattern: '^[+]*[(]{0,1}[0-9]{1,4}[)]{0,1}[-s./0-9]*$',
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'text',
    key: 'email',
    label: 'E-Mail',
    type: 'text',
    // options: [{key:'uno', value:'uno'}],
    value: '',
    order: 8,
    readonly: false,
    pattern:
      "^(?=.{1,254}$)(?=.{1,64}@)[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+(?:.[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+)*@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$",
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'text',
    key: 'pomeloId',
    label: 'Pomelo ID',
    type: 'text',
    // options: [{key:'uno', value:'uno'}],
    value: '',
    order: 9,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'text',
    key: 'occupation',
    label: 'Ocupación',
    type: 'text',
    value: '',
    order: 10,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'text',
    key: 'country',
    label: 'País',
    type: 'text',
    value: '',
    order: 11,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'text',
    key: 'nationality',
    label: 'Nacionalidad',
    type: 'text',
    value: '',
    order: 12,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'text',
    key: 'maritalStatus',
    label: 'Estado Civil',
    type: 'text',
    value: '',
    order: 13,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'text',
    key: 'neighborhood',
    label: 'Barrio',
    type: 'text',
    value: '',
    order: 14,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'text',
    key: 'floor',
    label: 'Piso',
    type: 'text',
    value: '',
    order: 15,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'text',
    key: 'apartment',
    label: 'Departamento',
    type: 'text',
    value: '',
    order: 16,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'text',
    key: 'streetName',
    label: 'Calle',
    type: 'text',
    value: '',
    order: 17,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'text',
    key: 'streetNumber',
    label: 'Numero',
    type: 'text',
    value: '',
    order: 18,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'text',
    key: 'zipCode',
    label: 'Código Postal',
    type: 'text',
    value: '',
    order: 19,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'text',
    key: 'city',
    label: 'Ciudad',
    type: 'text',
    value: '',
    order: 20,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'text',
    key: 'state',
    label: 'Estado',
    type: 'text',
    value: '',
    order: 21,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'text',
    key: 'politicalPerson',
    label: 'Persona Política',
    type: 'text',
    value: '',
    order: 22,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'text',
    key: 'obligatedSubject',
    label: 'Sujeto Obligado',
    type: 'text',
    value: '',
    order: 23,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'text',
    key: 'systemVersion',
    label: 'Versión APP',
    type: 'text',
    value: '',
    order: 24,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'text',
    key: 'notes',
    label: 'Notas',
    type: 'text',
    value: '',
    order: 25,
    readonly: false,
  }),
];

//fieldsSave
let fieldsSave = [
  new FieldBase<any>({
    required: false,
    url: '',
    text: '',
    controlType: 'textbox',
    key: 'id',
    label: '',
    type: 'hidden',
    value: '',
    order: 101,
    showLabel: false,
    readonly: true,
  }),

  new FieldBase<any>({
    required: true,
    url: '',
    text: '',
    controlType: 'textbox',
    key: 'name',
    label: '',
    type: 'text',
    value: '',
    order: 1,
    showLabel: true,
    readonly: false,
  }),
  new FieldBase<any>({
    required: true,
    url: '',
    text: '',
    controlType: 'select',
    key: 'status',
    label: '',
    type: 'select',
    options: [
      { key: 'pending', value: 'pending' },
      { key: 'enable', value: 'enable' },
      { key: 'disable', value: 'disable' },
    ],
    value: 'enable',
    order: 2,
    showLabel: true,
    readonly: false,
  }),
  new FieldBase<any>({
    required: true,
    url: '',
    text: '',
    controlType: 'select',
    key: 'access',
    label: '',
    type: 'select',
    options: [
      { key: 'administrator', value: 'administrator' },
      { key: 'supervisor', value: 'supervisor' },
      { key: 'operator', value: 'operator' },
      { key: 'customer', value: 'customer' },
      { key: 'user', value: 'user' },
    ],
    value: 'customer',
    order: 3,
    showLabel: true,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'text',
    key: 'phone',
    label: '',
    type: 'text',
    // options: [],
    value: '',
    order: 6,
    readonly: false,
    pattern: '^[+]*[(]{0,1}[0-9]{1,4}[)]{0,1}[-s./0-9]*$',
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'text',
    key: 'email',
    label: '',
    type: 'text',
    value: '',
    order: 7,
    readonly: false,
    pattern:
      "^(?=.{1,254}$)(?=.{1,64}@)[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+(?:.[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+)*@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$",
  }),
  new FieldBase<any>({
    showLabel: true,
    required: true,
    url: '',
    text: '',
    controlType: 'text',
    key: 'username',
    label: '',
    type: 'text',
    value: '',
    order: 8,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: true,
    url: '',
    text: '',
    controlType: 'text',
    key: 'password',
    label: '',
    type: 'password',
    value: '',
    order: 9,
    readonly: false,
    pattern: '^(?=.*[a-zA-Z])(?=.*[0-9]).{6,}$',
    msj: 'La clave debe tener al menos 6 caracteres, contener letras y números'

  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'text',
    key: 'notes',
    label: 'Notas',
    type: 'text',
    value: '',
    order: 10,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'link1',
    key: 'link1',
    label: '',
    type: 'hidden',
    value: '',
    order: 11,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'link2',
    key: 'link2',
    label: '',
    type: 'hidden',
    value: '',
    order: 12,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'link3',
    key: 'link3',
    label: '',
    type: 'hidden',
    value: '',
    order: 13,
    readonly: false,
  }),
  new FieldBase<any>({
    showLabel: true,
    required: false,
    url: '',
    text: '',
    controlType: 'link4',
    key: 'link4',
    label: '',
    type: 'hidden',
    value: '',
    order: 14,
    readonly: false,
  }),
];

// Configuración Mostrar
const ConfigShow: FormTemplate = {
  title: 'Usuario',
  action: ACTION_FORM.SHOW,
  post_url: urls.post,
  show_url: urls.get,
  id: '',
  fields: fieldsShow,
};

// Configuración Editar
const ConfigEdit: FormTemplate = {
  title: 'Editar usuario',
  action: ACTION_FORM.EDIT,
  post_url: urls.post,
  show_url: urls.get,
  id: '',
  fields: fieldsEdit,
};

// Configuración Save
const ConfigSave: FormTemplate = {
  title: 'Crear usuario',
  action: ACTION_FORM.SAVE,
  post_url: urls.post,
  show_url: urls.get,
  id: '',
  fields: fieldsSave,
};

export const ConfigurationUsuario: FormTemplate[] = [
  ConfigShow,
  ConfigEdit,
  ConfigSave,
];

export const Search = [
  {
    property: { es: 'Ordenar por', en: 'order' },
    match: [
      { label: { es: 'Nombre', en: 'name' } },
      { label: { es: 'Fecha de actualización', en: 'updatedAt' } },
      { label: { es: 'Fecha de creación', en: 'createdAt' } },
    ],
    value: 'name',
  },
  {
    property: { es: 'Estado', en: 'state' },
    match: [
      { label: { es: 'Pendiente', en: 'pending' } },
      { label: { es: 'Habilitado', en: 'enable' } },
      { label: { es: 'Deshabilitado', en: 'disable' } },
    ],
    value: '',
  },
];
